# Generated by Django 4.0.1 on 2022-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzivatele',
            name='vek',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
