# Generated by Django 4.0.1 on 2022-04-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uzivatele_vek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatele',
            old_name='vek',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='uzivatele',
            old_name='name',
            new_name='jmeno',
        ),
    ]
